### ISSUE TITLE
Demand Analysis

### ISSUE THREAD

**Issue by IsumiF** [IsumiF/file-collector#1]
完成初步的需求分析

**Comment by IsumiF** [comment]
我在分支"demand_analysis"创建了空的"doc/demand_analysis.md"文件。需求分析可以写在这个markdown文档里。

**Comment by IsumiF** [comment]
我们不妨采用[这个](https://github.com/kowainik/org#workflow)workflow。对每个任务，创建对应的issue。每个commit在message开头带上[#IssueId]，用以标记关联的issue。例如[#1]表示1号issue

**Comment by Lagrand** [comment]
需求分析初稿已经完成。接下来需要更详细的use case specification
