### ISSUE TITLE
Create REST API specification

### ISSUE THREAD

**Issue by IsumiF** [IsumiF/file-collector#4]
我们需要一个REST API文档，从而使前后端的开发可以开始各自进行。API文档可以先用markdown打个草稿（放在doc目录下）
不过我们需要考虑后续API文档怎样编写。例如Haskell里面可以使用servant描述API，接着生成相应的前后端代码和文档。我们首先应当确定使用什么工具来编写API文档，Swagger? Spring REST Docs?

**Comment by IsumiF** [comment]
可以直接用servant来描述API，这样前端如果是JS/TS，可以考虑生成调用函数；后端未来也可以实现一个Haskell版

**Comment by Lagrand** [comment]
这样有机会的话前端可以用reflex-frp来做，正好这学期学了CSS，不必完全依赖React的MaterialUI控件库
